/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

public class PanelDeJuego extends JPanel {

    private JButton[][] casillas = new JButton[8][8];
    
    // Nueva: Matriz numerica para saber en donde carajo esta cada ficha
    private int[][] matrizLogica = new int[8][8];

    public PanelDeJuego() {
        this.setLayout(new GridLayout(8, 8));
        inicializarTablero();
        ResetearTablero();         // 1. Coloca los numeros en la matriz logica
        dibujar_en_los_botones(); // 2. Pinta las fichas en la pantalla basandose en esos numeros
    }

    private void inicializarTablero() {
        for (int fila = 0; fila < 8; fila++) {
            for (int col = 0; col < 8; col++) {
                casillas[fila][col] = new JButton();
                
                if ((fila + col) % 2 == 0) {
                    casillas[fila][col].setBackground(Color.WHITE);
                } else {
                    casillas[fila][col].setBackground(Color.DARK_GRAY);
                }
                
                casillas[fila][col].setFocusable(false);
                this.add(casillas[fila][col]);
            }
        }
    }

    // Llenamos la matriz con las posiciones iniciales del juego
    public void ResetearTablero() {
        for (int fila = 0; fila < 8; fila++) {
            for (int col = 0; col < 8; col++) {
                matrizLogica[fila][col] = 0; // Por defecto todo vacio
                
                // Las damas solo van en las casillas oscuras (impares)
                if ((fila + col) % 2 != 0) {
                    if (fila < 3) {
                        matrizLogica[fila][col] = 1; // Fichas del jugador de arriba (Negras)
                    } else if (fila > 4) {
                        matrizLogica[fila][col] = 2; // Fichas del jugador de abajo (Rojas)
                    }
                }
            }
        }
    }

    // Lee la matriz numerica y dibuja los circulos ● correspondientes
    public void dibujar_en_los_botones() {
        for (int fila = 0; fila < 8; fila++) {
            for (int col = 0; col < 8; col++) {
                int estadoCasilla = matrizLogica[fila][col];
                
                if (estadoCasilla == 1) {
                    casillas[fila][col].setText("●");
                    casillas[fila][col].setForeground(Color.BLACK); // Ficha Negra
                    casillas[fila][col].setFont(new Font("Arial", Font.BOLD, 35)); // Circulo grande
                } else if (estadoCasilla == 2) {
                    casillas[fila][col].setText("●");
                    casillas[fila][col].setForeground(Color.RED);   // Ficha Roja
                    casillas[fila][col].setFont(new Font("Arial", Font.BOLD, 35));
                } else {
                    casillas[fila][col].setText(""); // Si es 0, borra el texto (casilla vacia)
                }
            }
        }
    }


    public void RecibirMovimientoParticipante(int fOrigen, int cOrigen, int fDestino, int cDestino) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        //</editor-fold>
         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
